config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :movies
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, :uniqueness => { :scope => :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  def show

  end

  def new
    @list = List.new
  end

  def edit

  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    if @list.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name, :movie_id, :bookmark_id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update ]

  # GET /movies or /movies.json
  def index
    if params[:query].present?
      sql_query = 'title ILIKE :query OR overview ILIKE :query'
      @movies = Movie.where(sql_query, query: "%#{params[:query]}%")
    else
      @movies = Movie.all
    end
  end

  # GET /movies/1 or /movies/1.json
  def show

  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.save
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    @movie.update(movie_params)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit(:title, :overview, :rating, :poster_url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_bookmark.html.erb
<div id="<%= dom_id bookmark %>">
  <p>
    <strong>Comment:</strong>
    <%= bookmark.comment %>
  </p>

</div>

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>

  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/bookmarks/_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
<div class="modal fade" data-controller ="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Update</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "bookmarks/form", list: @list %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/bookmarks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookmarks</h1>

<div id="bookmarks">
  <% @bookmarks.each do |bookmark| %>
    <%= render bookmark %>
  <% end %>
</div>

app/views/bookmarks/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "bookmarks/modal", locals: { list: @list }%>
<% end %>

app/views/bookmarks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bookmark %>

<div>
  <%= link_to "Edit this bookmark", edit_bookmark_path(@bookmark) %> |
  <%= link_to "Back to bookmarks", bookmarks_path %>
  <%= button_to "Destroy this bookmark", @bookmark, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%# <meta name="viewport" content="width=device-width,initial-scale=1"> %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  </head>

  <body>
    <%= yield %>
    <%= turbo_frame_tag "remote_modal" %>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner">
  <div>
    <h1>My Movie Lists</h1>
    <p><span data-controller="typed-js"></span></p>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>

    <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div data-aos ="fade-down" class="list-card" style ="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://source.unsplash.com/random/?<%= list.name%> movies')">
  <p>
    <h2><%= list.name.capitalize %></h2>
  </p>
</div>

app/views/lists/_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
<div class="modal fade" data-controller ="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Update</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "form", list: @list %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/lists/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "lists/modal", locals: { list: @list }%>
<% end %>

app/views/lists/index.html.erb
<div class="home-navbar">
  <%= link_to "+ New list", new_list_path, class:"button-list", "data-controller":"turbo" %>
  <%= link_to "View All Movies", movies_path, class:"button-list" %>
</div>
<%= render "banner" %>
<div class="lists">
    <% @lists.each do |list| %>
        <%= link_to list do %>
          <%= render list %>
        <% end %>
      <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>

  <%= render "form", list: @list %>

  <br>

  <div>
    <%= link_to "Back to lists", lists_path %>
  </div>
</div>

app/views/lists/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "lists/modal", locals: { list: @list }%>
<% end %>

app/views/lists/show.html.erb
<div class="show-navbar">
    <%= link_to "Home", lists_path, class: "button-show" %>
    <%= link_to "Edit this list", edit_list_path(@list), "data-controller":"turbo", class: "button-show" %>
</div>

<div class="show-banner" style ="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80)" >
  <h1><%= @list.name.capitalize %></h1>
</div>

<div class="container">
<%= link_to "Add Movie", new_list_bookmark_path(@list), class:"button-show", "data-controller":"turbo"  %>
<%= link_to "Destroy this list", @list, data: {turbo_method: :delete}, class:"button-show" %>
    <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <div class="show-cards" data-aos= "fade-down">
      <%= image_tag movie.poster_url %>
      <div class="show-card-info">
        <div class="show-card-title">
          <h2><%= movie.title %></h2>&nbsp<span><%= movie.rating%>⭐</span>
        </div>
        <p class="show-overview"><i><%= movie.overview %></i></p>
        <div class="show-card-footer">
          <h4><i class="fa-sharp fa-solid fa-quote-left">&nbsp</i><%= bookmark.comment %>&nbsp<i class="fa-sharp fa-solid fa-quote-right"></i></h4>
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete} do %>
            <i class="fa-solid fa-dumpster"></i>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>

    <div class="show-review" data-aos = "fade-up">
      <div class="show-review-header">
        <h2><%= @list.name %> List Reviews</h2>
        <%= link_to "+ Add Review", new_list_review_path(@list), "data-controller":"turbo", class:"button-review" %>
      </div>
      <div class="show-review-content">

      <% @list.reviews.each do |review| %>
        <h4><i class="fa-sharp fa-solid fa-quote-left">&nbsp</i><%= review.content %>&nbsp<i class="fa-sharp fa-solid fa-quote-right"></i></h4> <span><%= review.created_at %></span>
        <p><%= "⭐" * review.rating%></p>
      <% end %>
      </div>
    </div>
</div>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :overview %>
    <%= f.input :rating %>
    <%= f.input :poster_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Overview:</strong>
    <%= movie.overview %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <strong>Poster url:</strong>
    <%= movie.poster_url %>
  </p>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <h1>Movies</h1>

  <form id="search-form" class="row">
    <div class="col-10">
      <input id="search-input" type="text" class="form-control" placeholder="Find movies">
    </div>
    <div class="col-2">
      <input type="submit" class="btn btn-primary" value="Search">
    </div>
  </form>

  <ul id="results" class="list-inline" data-controller = "search">

  </ul>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/reviews/_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
<div class="modal fade" data-controller ="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Update</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "new", list: @list, review: @review %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/reviews/_new.html.erb
<%= simple_form_for [@list, @review]  do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
  <%= f.submit "Send your review", class:"btn btn-primary" %>
<% end %>

app/views/reviews/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "reviews/modal", locals: { list: @list, review: @review }%>
<% end %>